snakes_data = [
    {
      "common_name": "Western Terrestrial Garter Snake",
      "scientific_name": "thamnophis-elegans",
      "venomous": "Non-venomous",
      "antivenom": "Not Required any Antivenom",
      "Habitat and Distribution": "The Western terrestrial garter snake is found in a wide range of habitats, from grasslands and forests to wetlands and suburban areas. It is commonly found across the western United States, parts of Canada, and northern Mexico. It is highly adaptable and can live in environments ranging from sea level to mountainous regions.",
      "diet": "This species has a varied diet that includes amphibians, fish, earthworms, slugs, and small mammals. They are also known to eat other snakes, including their own species. Some populations of the Western terrestrial garter snake have developed resistance to the toxins of certain amphibians, such as the rough-skinned newt, which they can eat without harm.",
      "behavior": "Western terrestrial garter snakes are diurnal, meaning they are active during the day. They are often seen basking in the sun to regulate their body temperature. When threatened, they can emit a foul-smelling musk from their anal glands as a defense mechanism to deter predators.",
      "reproduction": "These snakes give birth to live young, a trait known as ovoviviparity. Females typically give birth to a litter of 4 to 20 young, depending on the size of the female and environmental conditions. Mating usually occurs in the spring after they emerge from hibernation, and females store sperm until they are ready to fertilize their eggs.",
      "defense_mechanisms": "In addition to musking, they may flatten their heads to mimic a more dangerous snake, like a rattlesnake, and sometimes even strike, though they are non-venomous and harmless to humans.",
      "management": "In case of non venomous snake bites, only local wound care( The bite wound is cleaned with povidone iodine solution and left open without any dressing. Blisters, if present, should not be punctured. In case local tissue necrosis and sloughing occurs, it should be debrided and a saline dressing placed over it.) and a tetanus injection administration is required",
      "link": "https://en.wikipedia.org/wiki/Western_terrestrial_garter_snake",

    },
    {
      "common_name": "Checkered Garter Snake",
      "scientific_name": "thamnophis-marcianus",
      "venomous": "Non-venomous",
      "antivenom": "Not Required any Antivenom",
      "Habitat and Distribution": "The Checkered garter snake is primarily found in the southwestern United States, including Texas, New Mexico, and Arizona, as well as in Mexico and parts of Central America.It thrives in a variety of habitats, such as grasslands, savannas, deserts, and near water sources like rivers, streams, and ponds.",
      "diet": "This species has a varied diet, feeding on amphibians, fish, earthworms, small mammals, and occasionally insects. Like other garter snakes, it is opportunistic and will eat whatever prey is available.The Checkered garter snake is also known to feed on toads, and it has some resistance to the toxins found in toad skin, allowing it to consume them without harm.",
      "behavior": "Checkered garter snakes are diurnal and active during the day, especially in the morning and late afternoon. They are often seen basking in the sun to regulate their body temperature.When threatened, they may flatten their bodies and release a foul-smelling musk from their cloacal glands as a defense mechanism. They can also be quite fast and agile, making them difficult for predators to catch.",
      "reproduction": "These snakes are ovoviviparous, meaning females give birth to live young. A typical litter consists of 10 to 40 babies, depending on the size and health of the female.Mating usually occurs in the spring, and the young are born in late summer or early fall. The newborns are independent from birth and must fend for themselves.",
      "adaptability": "The Checkered garter snake is highly adaptable to different environments and can often be found in areas close to human habitation, such as agricultural fields and suburban gardens.They are also known to be good swimmers and can escape predators by diving into water and swimming away quickly.",
      "management": "In case of non venomous snake bites, only local wound care( The bite wound is cleaned with povidone iodine solution and left open without any dressing. Blisters, if present, should not be punctured. In case local tissue necrosis and sloughing occurs, it should be debrided and a saline dressing placed over it.) and a tetanus injection administration is required",
      "link": "https://en.wikipedia.org/wiki/Checkered_garter_snake",
    },
    {
      "common_name": "Corn Snake",
      "scientific_name": "pantherophis-guttatus",
      "venomous": "Non-venomous",
      "antivenom": "Not Required any Antivenom",
      "Habitat and Distribution": "Corn snakes are commonly found in the southeastern United States, ranging from New Jersey to Florida and westward to Texas.They inhabit a variety of environments, including woodlands, grasslands, rocky hillsides, and abandoned buildings. They are often found near agricultural areas, particularly cornfields, which is how they got their name.",
      "diet": "In the wild, Corn snakes primarily feed on small rodents like mice and rats, which they kill by constriction. They are also known to eat birds, bird eggs, and occasionally lizards.Due to their diet, Corn snakes are beneficial to farmers as they help control rodent populations in agricultural areas.",
      "behavior": "Corn snakes are primarily nocturnal or crepuscular, meaning they are most active during the evening and early morning hours. However, they can also be active during the day, especially in cooler weather.They are excellent climbers and often seek shelter in trees, under logs, or in abandoned buildings.",
      "reproduction": "Corn snakes are oviparous, meaning they lay eggs. Females typically lay 10 to 30 eggs in late spring or early summer, in warm, moist environments such as decaying vegetation or rotting logs.The eggs hatch after about 60 to 70 days, and the hatchlings are independent from birth, requiring no parental care.",
      "defense_mechanisms": "Corn snakes have excellent camouflage, which helps them avoid predators. Their coloration allows them to blend in with fallen leaves and forest floors.When threatened, they may vibrate their tails in dry leaves to mimic the sound of a rattlesnake, a behavior that can deter potential predators.",
      "management": "In case of non venomous snake bites, only local wound care( The bite wound is cleaned with povidone iodine solution and left open without any dressing. Blisters, if present, should not be punctured. In case local tissue necrosis and sloughing occurs, it should be debrided and a saline dressing placed over it.) and a tetanus injection administration is required",
      "link": "https://en.wikipedia.org/wiki/Corn_snake",
    },
    {
      "common_name": "Timber Rattlesnake",
      "scientific_name": "crotalus-horridus",
      "venomous": "venomous",
      "antivenom": "CroFab",
      "Habitat and Distribution": "The Timber Rattlesnake is found across the eastern United States, from southern Maine to Florida and westward to eastern Texas and southern Missouri. It is common in deciduous forests, mixed woodlands, and hilly or mountainous regions.It prefers habitats with ample ground cover, such as leaf litter, logs, and rocky outcrops, which provide both shelter and hunting grounds.",
      "diet": "The Timber Rattlesnake primarily preys on small to medium-sized mammals, including rodents, squirrels, and rabbits. It may also eat birds, amphibians, and other small animals.It uses its venom to immobilize and begin digesting its prey before swallowing it whole. The venom contains both hemotoxins and neurotoxins that help break down tissues and facilitate digestion.",
      "behavior": "Timber Rattlesnakes are generally solitary and are most active during the warmer months, from spring through fall. They are primarily crepuscular or nocturnal, meaning they are most active during dawn, dusk, and nighttime.During colder months, they hibernate in communal dens, which are often located in rocky outcrops or burrows. These dens are shared with other rattlesnakes, and individuals may remain in these dens for several months during winter.",
      "reproduction": "The Timber Rattlesnake is ovoviviparous, meaning it gives birth to live young rather than laying eggs. Mating occurs in the spring, and females give birth to litters of 6 to 14 live young in late summer or early fall.The young are about 8 to 10 inches (20 to 25 cm) long at birth and are born with fully functional venom and a small rattle, which is initially unsegmented.",
      "Venom and Defense": "The venom of the Timber Rattlesnake is potent and can cause significant damage to tissues and disrupt blood clotting. However, bites to humans are rarely fatal due to the availability of antivenom and prompt medical treatment.The rattle is used as a warning device to alert potential threats of the snake’s presence. If the threat does not retreat, the rattlesnake may strike in defense.",
      "Interesting_Fact": "Timber Rattlesnakes have a remarkable ability to detect heat. They possess specialized pit organs located between their eyes and nostrils that allow them to sense the infrared radiation emitted by warm-blooded prey, making them highly effective nocturnal hunters.",
      "link": "https://en.wikipedia.org/wiki/Timber_rattlesnake",
    },
    {
      "common_name": "Plains Garter Snake",
      "scientific_name": "thamnophis-radix",
      "venomous": "Non-venomous",
      "antivenom": "Not Required any Antivenom",
      "Habitat and Distribution": "The Plains garter snake is primarily found in the central United States, including states like Kansas, Nebraska, Colorado, Wyoming, and extending into southern Canada.It thrives in open habitats such as grasslands, prairies, and marshes, as well as near bodies of water like ponds, streams, and wetlands. It is often found in suburban and agricultural areas as well.",
      "diet": "The Plains garter snake has a varied diet that includes amphibians (like frogs and toads), earthworms, small fish, and occasionally small mammals and insects.Like other garter snakes, they have some resistance to the toxins of certain amphibians, allowing them to prey on species that other predators might avoid.",
      "behavior": "Plains garter snakes are diurnal, meaning they are active during the day. They are often seen basking in the sun to regulate their body temperature or foraging for food.When threatened, they may release a foul-smelling musk from their cloacal glands as a defense mechanism to deter predators.",
      "reproduction": "These snakes are ovoviviparous, meaning they give birth to live young rather than laying eggs. A female typically gives birth to a litter of 10 to 20 young, though larger litters are possible.Mating usually occurs in the spring, and the young are born in late summer or early fall. The newborn snakes are independent from birth.",
      "defense_mechanisms": "In addition to musking, Plains garter snakes may flatten their bodies and head to appear larger and more threatening. They can also be quick and agile, making it difficult for predators to capture them.They rarely bite when handled, but like most wild animals, they prefer to be left alone and will defend themselves if they feel threatened.",
      "Interesting_Fact": "Plains garter snakes have been known to exhibit communal hibernation, where many individuals gather together in a single hibernaculum (a den used for hibernation) during the winter months to conserve warmth and protect against the cold.",
      "management": "In case of non venomous snake bites, only local wound care( The bite wound is cleaned with povidone iodine solution and left open without any dressing. Blisters, if present, should not be punctured. In case local tissue necrosis and sloughing occurs, it should be debrided and a saline dressing placed over it.) and a tetanus injection administration is required",
      "link": "https://en.wikipedia.org/wiki/Plains_garter_snake",
    },
    {
      "common_name": "Red-bellied Snake",
      "scientific_name": "storeria-occipitomaculata",
      "venomous": "Non-venomous",
      "antivenom": "Not Required any Antivenom",
      "Habitat and Distribution": "The Red-bellied snake is found across much of eastern North America, ranging from Canada down through the eastern United States and into parts of the Midwest.It typically inhabits moist, wooded areas, such as forests, swamps, and marshes. They are often found under logs, rocks, leaf litter, or other debris.",
      "diet": "Red-bellied snakes primarily feed on small invertebrates, including slugs, earthworms, and insects. They are particularly known for their ability to consume slugs, which are a major part of their diet.Their specialized diet helps control slug populations, making them beneficial for gardeners.",
      "behavior": "These snakes are mostly nocturnal and are often active during the evening and night. They are also fossorial, meaning they spend a lot of time hidden under leaf litter, soil, or other debris.When threatened, Red-bellied snakes may coil up, flatten their bodies, and display their brightly colored belly as a warning signal to predators. This behavior is thought to deter predators by suggesting that the snake may be toxic, even though it is harmless.",
      "reproduction": "Red-bellied snakes are viviparous, meaning they give birth to live young. A female typically gives birth to a litter of 3 to 12 young in late summer or early fall.The newborn snakes are independent from birth and must fend for themselves, although they are born fully equipped to hunt for small prey.",
      "Interesting_Fact": "Red-bellied snakes have a unique adaptation for surviving cold climates. They can often be found hibernating in large numbers in communal dens, sometimes with other snake species, to maintain warmth during the winter months.",
      "management": "In case of non venomous snake bites, only local wound care( The bite wound is cleaned with povidone iodine solution and left open without any dressing. Blisters, if present, should not be punctured. In case local tissue necrosis and sloughing occurs, it should be debrided and a saline dressing placed over it.) and a tetanus injection administration is required",
      "link": "https://en.wikipedia.org/wiki/Storeria_occipitomaculata",
    },
    {
      "common_name": "Eastern Hog-nosed Snake",
      "scientific_name": "heterodon-platirhinos",
      "venomous": "Non-venomous",
      "antivenom": "Not Required any Antivenom",
      "Habitat and Distribution": "The Eastern hog-nosed snake is found across much of the eastern United States, from New England to Florida, and westward to the Great Plains. It is also found in parts of southern Canada.It prefers sandy or loose soils where it can easily dig, and it is commonly found in fields, woodlands, prairies, and coastal areas. These snakes are often associated with areas that have abundant toad populations, which are a major part of their diet.",
      "diet": "Eastern hog-nosed snakes have a specialized diet, feeding primarily on amphibians, particularly toads. They are resistant to the toxins that toads secrete as a defense mechanism, allowing them to consume these amphibians without harm.They may also eat frogs, salamanders, small mammals, birds, and occasionally insects, but toads are their preferred prey.",
      "behavior": "The Eastern hog-nosed snake is famous for its dramatic defensive behaviors. When threatened, it may first flatten its head and neck, hiss loudly, and strike with a closed mouth, mimicking a cobra. This behavior has earned it the nickname puff adder, although it is not venomous.If the initial threat display doesn't work, the snake may perform an even more dramatic act: it will roll onto its back, convulse, and play dead, often with its mouth open and tongue hanging out. This behavior is known as thanatosis, and it is designed to make the snake appear unappetizing to predators.Despite these defensive displays, Eastern hog-nosed snakes are harmless to humans and rarely bite.",
      "reproduction": "Eastern hog-nosed snakes are oviparous, meaning they lay eggs. A female typically lays 10 to 30 eggs in sandy or loose soil during the early summer. The eggs hatch after about 50 to 65 days.The hatchlings are independent from birth and measure about 6 to 9 inches (15 to 23 cm) in length. They are born fully equipped to hunt small prey.",
      "Interesting_Fact": "The Eastern hog-nosed snake's resistance to toad toxins is an evolutionary adaptation that allows it to exploit a food source that many other predators avoid. This specialization has helped the snake carve out a unique niche in its ecosystem.",
      "management": "In case of non venomous snake bites, only local wound care( The bite wound is cleaned with povidone iodine solution and left open without any dressing. Blisters, if present, should not be punctured. In case local tissue necrosis and sloughing occurs, it should be debrided and a saline dressing placed over it.) and a tetanus injection administration is required",
      "link": "https://en.wikipedia.org/wiki/Eastern_hognose_snake",
    },
    {
      "common_name": "North American Racer",
      "scientific_name": "coluber-constrictor",
      "venomous": "Non-venomous",
      "antivenom": "Not Required any Antivenom",
      "Habitat and Distribution": "The North American racer is widely distributed across the United States, southern Canada, and parts of Mexico. It is one of the most widespread snake species in North America.Racers are highly adaptable and can be found in a variety of habitats, including grasslands, forests, wetlands, agricultural fields, and suburban areas. They prefer open, sunny areas where they can bask and hunt.",
      "Speed and Agility": "True to their name, North American racers are among the fastest snakes in North America. They can move at speeds of up to 4 miles per hour (6.4 km/h), making them adept at escaping predators and catching prey.They are also excellent climbers and swimmers, often seen chasing prey through bushes, trees, or water.",
      "diet": "North American racers have a diverse diet, feeding on a wide range of prey, including insects, frogs, lizards, small mammals, birds, and other snakes.Unlike constrictors, racers subdue their prey by pinning it down with their coils and then swallowing it alive. They rely on their speed and agility to capture prey rather than constriction.",
      "behavior": "Racers are diurnal, meaning they are active during the day. They are most commonly seen basking in the sun or hunting for food in open areas.When threatened, a racer may flee quickly, but if cornered, it can become quite defensive. It may vibrate its tail, strike repeatedly, and even emit a foul-smelling musk to deter predators. Despite this aggressive behavior, they are non-venomous and harmless to humans.",
      "reproduction": "North American racers are oviparous, meaning they lay eggs. Mating occurs in the spring, and females lay clutches of 6 to 20 eggs in early summer in hidden, warm locations such as under logs, in leaf litter, or in abandoned burrows.The eggs hatch after about 2 to 2.5 months, usually in late summer or early fall. The hatchlings are fully independent from birth and resemble the blotched pattern of juvenile racers.",
      "Interesting_Fact": "The black racer is often confused with the black rat snake (Pantherophis obsoletus), but the two can be distinguished by their behavior and physical characteristics. Racers are more slender, have smoother scales, and are much more active during the day, while black rat snakes are typically more docile and have keeled (ridged) scales.",
      "management": "In case of non venomous snake bites, only local wound care( The bite wound is cleaned with povidone iodine solution and left open without any dressing. Blisters, if present, should not be punctured. In case local tissue necrosis and sloughing occurs, it should be debrided and a saline dressing placed over it.) and a tetanus injection administration is required",
      "link": "https://en.wikipedia.org/wiki/Eastern_racer",
    },
    {
      "common_name": "Milk Snake",
      "scientific_name": "lampropeltis-triangulum",
      "venomous": "Non-venomous",
      "antivenom": "Not Required any Antivenom",
      "Habitat and Distribution": "Milk snakes have one of the broadest ranges of any snake species, occurring from southeastern Canada through the eastern and central United States, down into Central America, reaching as far south as northern South America.They are highly adaptable and can be found in a wide variety of habitats, including forests, grasslands, rocky hillsides, farmlands, and even urban areas. They are often found in or around barns and other structures, which is how they got their name.",
      "diet": "Milk snakes are opportunistic feeders, consuming a diet that includes small mammals, birds, eggs, lizards, amphibians, and other snakes. They are constrictors, meaning they coil around their prey and squeeze it until it suffocates.Their diet helps control populations of rodents and other small animals, making them beneficial to farmers and homeowners.",
      "behavior": "Milk snakes are primarily nocturnal, especially during the warmer months, although they can be active during the day in cooler weather.They are secretive and often hide under rocks, logs, or other debris. In colder climates, they hibernate during the winter months in burrows or other underground shelters.When threatened, milk snakes may vibrate their tails, which can produce a sound similar to a rattlesnake if they are in dry leaves or grass. This behavior is intended to deter predators, even though they are non-venomous.",
      "reproduction": "Milk snakes are oviparous, laying clutches of 6 to 24 eggs in early summer in hidden locations such as under logs, in decaying vegetation, or in burrows.The eggs hatch after 6 to 10 weeks, and the young snakes are independent from birth. Hatchlings are typically 5 to 8 inches (13 to 20 cm) long and resemble the adults in coloration.",
      "defense_mechanisms": "The milk snake’s resemblance to the venomous coral snake is a classic example of Batesian mimicry, which helps protect it from predators. The bright coloration signals potential danger, even though the milk snake is harmless.If threatened, milk snakes may also flatten their bodies and release a foul-smelling musk as a further deterrent.",
      "Interesting_Fact": "The name ""milk snake"" comes from a myth that these snakes would enter barns and drink milk from cows. Of course, this is not true, as snakes are not capable of digesting milk and would not seek it out as food.",
      "management": "In case of non venomous snake bites, only local wound care( The bite wound is cleaned with povidone iodine solution and left open without any dressing. Blisters, if present, should not be punctured. In case local tissue necrosis and sloughing occurs, it should be debrided and a saline dressing placed over it.) and a tetanus injection administration is required",
      "link": "https://en.wikipedia.org/wiki/Milk_snake",
    },
    {
      "common_name": "Rough Earth Snake",
      "scientific_name": "Virginia striatula",
      "venomous": "Non-venomous",
      "antivenom": "Not Required any Antivenom",
      "Habitat and Distribution": "The Rough Earth Snake is found primarily in the southeastern United States, ranging from Texas to Virginia and down to Florida.It prefers moist, forested habitats with loose, loamy soil, such as woodlands, gardens, and suburban areas. They are often found under leaf litter, logs, rocks, and other debris where they can easily hide and forage for food.",
      "diet": "Rough Earth Snakes primarily feed on small invertebrates, with earthworms being their preferred prey. They also eat slugs, soft-bodied insects, and occasionally other small invertebrates.Their specialized diet makes them beneficial in controlling populations of garden pests like slugs and insects.",
      "behavior": "Rough Earth Snakes are fossorial, meaning they spend much of their time burrowing in loose soil, leaf litter, or under debris. This makes them difficult to spot, and they are rarely seen above ground except after heavy rains or during the breeding season.They are generally secretive and shy, preferring to avoid confrontation. When threatened, they may try to escape by burrowing into the soil or hiding under nearby cover.",
      "reproduction": "Rough Earth Snakes are viviparous, meaning they give birth to live young. Mating occurs in the spring, and females give birth to 3 to 8 live young in late summer.The newborn snakes are independent from birth and measure about 3 to 4 inches (7.5 to 10 cm) in length. They resemble the adults in coloration and behavior.",
      "Interesting_Fact": "Rough Earth Snakes are often mistaken for juvenile snakes of other species due to their small size and simple coloration. However, their keeled scales and consistent coloration throughout their life help distinguish them from other snakes.",
      "management": "In case of non venomous snake bites, only local wound care( The bite wound is cleaned with povidone iodine solution and left open without any dressing. Blisters, if present, should not be punctured. In case local tissue necrosis and sloughing occurs, it should be debrided and a saline dressing placed over it.) and a tetanus injection administration is required",
      "link": "https://en.wikipedia.org/wiki/Virginia_striatula",
    },
    {
      "common_name": "Ring-necked Snake",
      "scientific_name": "diadophis-punctatus",
      "venomous": "Non-venomous",
      "antivenom": "Not Required any Antivenom",
      "Habitat and Distribution": "The Ring-necked Snake is widespread throughout the United States, southeastern Canada, and parts of Mexico. It is one of the most commonly encountered snakes in many areas.It prefers moist, wooded environments with plenty of ground cover, such as forests, grasslands, and wetlands. They are often found under rocks, logs, leaf litter, and in crevices.These snakes are highly adaptable and can also be found in suburban areas, gardens, and parks.",
      "diet": "Ring-necked Snakes primarily feed on small invertebrates and vertebrates, including earthworms, slugs, small amphibians, lizards, and even other small snakes.They are constrictors, subduing their prey by coiling around it, but they also possess mild venom in their saliva that helps subdue their prey. This venom is delivered through enlarged rear teeth, making them technically rear-fanged snakes.",
      "behavior": "Ring-necked Snakes are primarily nocturnal and are most active at night. They are shy and secretive, spending much of their time hidden under cover or burrowing in loose soil or leaf litter.When threatened, they exhibit a distinctive defensive behavior: they curl their tail, exposing the bright underside, which may startle or confuse predators. This behavior, along with the snake's bright belly, serves as a warning signal to potential threats.Despite their venomous nature, Ring-necked Snakes are not dangerous to humans. Their venom is mild and not harmful to people, and they rarely, if ever, bite.",
      "reproduction": "Ring-necked Snakes are oviparous, meaning they lay eggs. Mating occurs in the spring, and females typically lay 3 to 10 eggs in late spring or early summer. The eggs are deposited in moist, hidden locations such as under logs, rocks, or in leaf litter.The eggs hatch after about two months, usually in late summer, and the hatchlings are about 3 to 4 inches (7.5 to 10 cm) long. They are independent from birth and resemble the adults in coloration and pattern.",
      "Interesting_Fact": "Despite their small size and secretive nature, Ring-necked Snakes are sometimes found in large communal groups, particularly during hibernation. It’s not uncommon to find dozens of these snakes sharing a hibernation site.",
      "management": "In case of non venomous snake bites, only local wound care( The bite wound is cleaned with povidone iodine solution and left open without any dressing. Blisters, if present, should not be punctured. In case local tissue necrosis and sloughing occurs, it should be debrided and a saline dressing placed over it.) and a tetanus injection administration is required",
      "link": "https://en.wikipedia.org/wiki/Ring-necked_snake",
    },
    {
      "common_name": "Common Garter Snake",
      "scientific_name": "thamnophis-sirtalis",
      "venomous": "Non-venomous",
      "antivenom": "Not Required any Antivenom",
      "Habitat and Distribution": "The Common Garter Snake is found throughout much of North America, from Canada and the United States to northern Mexico. It is particularly common in the eastern and central parts of the continent.This species is highly adaptable and can live in a wide range of habitats, including grasslands, forests, wetlands, and urban areas. It is often found near water sources such as ponds, streams, and marshes, where it can find prey and suitable basking sites.",
      "diet": "The diet of the Common Garter Snake is quite varied and includes small amphibians (frogs and toads), fish, earthworms, insects, and occasionally small mammals and birds.They are known for their ability to consume prey that is larger than their head due to their flexible jaws. Some populations specialize in feeding on amphibians, which they are well-adapted to hunt.",
      "behavior": "Common Garter Snakes are diurnal, meaning they are active during the day. They are often seen basking in the sun to regulate their body temperature.They are good swimmers and often hunt for prey in aquatic environments. They are also capable of climbing and may be found in low bushes or trees.When threatened, they may exhibit a defensive posture by flattening their bodies and hissing. If cornered, they might also release a foul-smelling musk from their cloacal glands as a deterrent to predators.",
      "reproduction": "The Common Garter Snake is viviparous, meaning it gives birth to live young rather than laying eggs. Mating occurs in the spring, and females give birth to litters of 10 to 40 live young in late summer or early fall.The young are born fully independent and measure about 6 to 8 inches (15 to 20 cm) in length. They resemble the adults in coloration but may have more subdued markings.",
      "Interesting_Fact": "Some populations of Common Garter Snakes are known to exhibit a fascinating form of mimicry known as “aposematic mimicry.” These snakes can mimic the appearance of more dangerous or venomous species to deter potential predators, even though they are harmless.",
      "management": "In case of non venomous snake bites, only local wound care( The bite wound is cleaned with povidone iodine solution and left open without any dressing. Blisters, if present, should not be punctured. In case local tissue necrosis and sloughing occurs, it should be debrided and a saline dressing placed over it.) and a tetanus injection administration is required",
      "link": "https://en.wikipedia.org/wiki/Common_garter_snake",
    },
    {
      "common_name": "Rough Green Snake",
      "scientific_name": "opheodrys-aestivus",
      "venomous": "Non-venomous",
      "antivenom": "Not Required any Antivenom",
      "Habitat and Distribution": "The Rough Green Snake is found throughout the southeastern United States, from North Carolina to Florida and westward to Texas. It is also present in parts of Mexico.This species prefers a variety of habitats, including woodlands, forests, shrubby areas, and areas near water such as swamps and marshes. It is often found in trees and shrubs, where it can blend in with the foliage.",
      "diet": "The Rough Green Snake primarily feeds on small insects and invertebrates, including spiders, caterpillars, crickets, and beetles. They also eat other small arthropods.It hunts by actively foraging through vegetation, using its keen vision to detect prey. Its diet is largely insectivorous, and it is well-adapted to catching small, agile prey in its arboreal environment.",
      "behavior": "The Rough Green Snake is primarily diurnal, meaning it is active during the day. It spends much of its time in trees and shrubs, where it can bask in the sun and hunt for food.It is a very agile climber and swimmer, moving effortlessly through its arboreal and aquatic habitats. It often uses its tail to grasp branches and maintain stability while navigating through vegetation.When threatened, the Rough Green Snake may attempt to escape rather than defend itself. It is generally non-aggressive and prefers to avoid confrontation.",
      "reproduction": "The Rough Green Snake is oviparous, meaning it lays eggs. Mating occurs in the spring, and females lay clutches of 4 to 12 eggs in summer, typically in hidden, moist locations such as under logs, in leaf litter, or in soil.The eggs hatch after about 2 to 3 months, and the hatchlings are about 5 to 7 inches (13 to 18 cm) long. They are independent from birth and resemble the adults in coloration but are smaller and more vulnerable.",
      "Interesting_Fact": "Despite their bright coloration and arboreal lifestyle, Rough Green Snakes are relatively shy and rarely come into contact with humans. They are more likely to be encountered by those exploring their natural habitats or while climbing trees and shrubs.",
      "management": "In case of non venomous snake bites, only local wound care( The bite wound is cleaned with povidone iodine solution and left open without any dressing. Blisters, if present, should not be punctured. In case local tissue necrosis and sloughing occurs, it should be debrided and a saline dressing placed over it.) and a tetanus injection administration is required",
      "link": "https://en.wikipedia.org/wiki/Opheodrys_aestivus",
    }
  ]